# Generated by Django 2.2.12 on 2022-06-09 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('verse', models.CharField(blank=True, max_length=100, null=True)),
                ('mp_verse', models.TextField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(default=datetime.datetime(2022, 6, 9, 16, 20, 7, 518709, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('detailed', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(default=datetime.datetime(2022, 6, 9, 16, 20, 7, 518147, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
