# Generated by Django 2.2.12 on 2022-06-10 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 17, 28, 47, 563113, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='detailed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 17, 28, 47, 562534, tzinfo=utc)),
        ),
    ]
