# Generated by Django 2.2.12 on 2022-06-10 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_auto_20220610_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='mp_verse',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 17, 31, 4, 150188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 17, 31, 4, 149587, tzinfo=utc)),
        ),
    ]
