# Generated by Django 4.0.3 on 2022-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goaladd_duration_length_alter_goaladd_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goaladd',
            old_name='duration_length',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='goaladd',
            name='duration',
        ),
        migrations.AlterField(
            model_name='goaladd',
            name='priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], help_text='low(1), medium(2) or high(3)'),
        ),
    ]
